## 导入所需要的包

In [129]:
import numpy as np 
import pandas as pd

In [6]:

indices = np.array([0,0,1,3,5],dtype=np.int_)
data=np.array([4.5,3.5,6.4,3.2,1.0],dtype=np.float64)
a=np.zeros(6,dtype=np.float64)
np.add.at(a,indices,data)

In [7]:
a

array([8. , 6.4, 0. , 3.2, 0. , 1. ])

### 爱因斯坦求和
单元矩阵组装的利器


In [ ]:
np.einsum # 一个函数搞定 矩阵 数组求和

In [ ]:
# 沿轴计算张量元素之和
# c=a.sum(axis=0)
c=np.einsum('ijk->jk',a) # 三维张量
c=np.einsum('i...->...',a) # 多于三维,可以将下标jk换成省略号,以表示剩下的所有维度

# 矩阵乘法
c=np.dot(a,b)
c=np.einsum('ij,jk->ik',a,b)

# 张量乘法的例子
c=np.einsum('ijk,ijl->kl',a,b)

In [42]:
np.random.seed(10)
a=np.random.rand(2,3,4)
b=np.random.rand(2,3,4)+1
display(a,b)

array([[[0.77132064, 0.02075195, 0.63364823, 0.74880388],
        [0.49850701, 0.22479665, 0.19806286, 0.76053071],
        [0.16911084, 0.08833981, 0.68535982, 0.95339335]],

       [[0.00394827, 0.51219226, 0.81262096, 0.61252607],
        [0.72175532, 0.29187607, 0.91777412, 0.71457578],
        [0.54254437, 0.14217005, 0.37334076, 0.67413362]]])

array([[[1.44183317, 1.43401399, 1.61776698, 1.51313824],
        [1.65039718, 1.60103895, 1.8052232 , 1.52164715],
        [1.90864888, 1.31923609, 1.09045935, 1.30070006]],

       [[1.11398436, 1.82868133, 1.04689632, 1.62628715],
        [1.54758616, 1.819287  , 1.19894754, 1.8568503 ],
        [1.35165264, 1.75464769, 1.29596171, 1.88393648]]])

In [43]:
np.einsum('ijk,ijk->k',a,b)

array([4.11233184, 2.22330895, 4.56492814, 7.1234104 ])

In [46]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[-1,-2,-3],[-4,-5,-6]])
display(a,b)

array([[1, 2, 3],
       [4, 5, 6]])

array([[-1, -2, -3],
       [-4, -5, -6]])

In [51]:
# a,b 维数相同,对应元素相乘再相加
np.einsum('ij,ij',a,b)

-91

In [47]:
np.einsum('ij,kj->ik',a,b) # 乘法

array([[-14, -32],
       [-32, -77]])

In [48]:
np.einsum('ij->',a) # 求和

21

In [50]:
# 矩阵转置
np.einsum('ij->ji',b)

array([[-1, -4],
       [-2, -5],
       [-3, -6]])

## 稀疏矩阵

In [ ]:
## 给定一个矩阵，如果其非零元素个数比较少，我们就称其为稀疏矩阵
## 如果矩阵的总数据量比较大，完成储存这个矩阵会有大量的0储存，会浪费很多空间。
# 因此，我们需要为稀疏矩阵设计不同的存储格式

In [ ]:
## 坐标格式 稀疏矩阵：Coordinate format Matrix(COO)
## 压缩稀疏行稀疏矩阵：Compressed Sparse Row Matrix(CSR)
## 压缩稀疏列稀疏矩阵：Compressed Sparse column Matrix(CSC)

In [54]:
from scipy.sparse import coo_matrix
from scipy.sparse import csr_matrix
from scipy.sparse import csc_matrix
## 存储是行优先

In [58]:
## coo_matrix 是最简单的稀疏矩阵存储方式，采用三元组(row, col, data)(或称为ijv format)的形式来存储矩阵中非零元素的信息
# 在实际使用中，一般coo_matrix用来创建矩阵，因为coo_matrix无法对矩阵的元素进行增删改操作；
# 创建成功之后可以转化成其他格式的稀疏矩阵（如csr_matrix、csc_matrix）进行转置、矩阵乘法等操作。

In [128]:
A=np.array([[0,0,0,10],[21,0,33,0],[0,0,0,0],[0,0,3,0],[12,1,0,4]])
display(A)
## coo展示
data=[10,21,33,3,12,1,4]
axis_0=[0,1,1,2,3,3,3]
axis_1=[3,0,2,2,0,1,3]
coo=coo_matrix((data,(axis_0,axis_1)),shape=(5,5))
display(coo,coo.toarray(),coo.todense())
# 通过toarray方法转化成密集矩阵(numpy.matrix)
# 通过todense方法转化成密集矩阵(numpy.matrix)

## csr 展示;高效的行切片
data=[10,21,33,3,12,1,4]
row_=[0,1,3,3,4,7]
column_=[3,0,2,2,0,1,3]
display(
    csr_matrix((data,column_,row_),shape=(5,4)).toarray()
    )

## csc 展示;高效的列切片
data=[21,12,1,33,3,10,4]
column_=[0,2,3,5,7]
row_=[1,4,4,1,3,0,4]
display(
    csc_matrix((data,row_,column_),shape=(5,4)).toarray()
    )

array([[ 0,  0,  0, 10],
       [21,  0, 33,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  3,  0],
       [12,  1,  0,  4]])

array([[ 0,  0,  0, 10],
       [21,  0, 33,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  3,  0],
       [12,  1,  0,  4]])

array([[ 0,  0,  0, 10],
       [21,  0, 33,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  3,  0],
       [12,  1,  0,  4]])

In [83]:
csr=coo.tocsr
display(csr)

<bound method coo_matrix.tocsr of <5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 7 stored elements in COOrdinate format>>

In [86]:
csr

<bound method coo_matrix.tocsr of <5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 7 stored elements in COOrdinate format>>

In [103]:
csc=coo.tocsc()
display(csc,csc.toarray())

<5x5 sparse matrix of type '<class 'numpy.intc'>'
	with 7 stored elements in Compressed Sparse Column format>

array([[ 0,  0,  0, 21,  0],
       [12,  0,  1,  0,  0],
       [ 0,  0, 33,  0,  0],
       [ 3, 10,  0,  4,  0],
       [ 0,  0,  0,  0,  0]], dtype=int32)

In [105]:
csr=coo.tocsr()
display(csr,csr.toarray())

<5x5 sparse matrix of type '<class 'numpy.intc'>'
	with 7 stored elements in Compressed Sparse Row format>

array([[ 0,  0,  0, 21,  0],
       [12,  0,  1,  0,  0],
       [ 0,  0, 33,  0,  0],
       [ 3, 10,  0,  4,  0],
       [ 0,  0,  0,  0,  0]], dtype=int32)

In [110]:
(csr+csr).toarray()

array([[ 0,  0,  0, 42,  0],
       [24,  0,  2,  0,  0],
       [ 0,  0, 66,  0,  0],
       [ 6, 20,  0,  8,  0],
       [ 0,  0,  0,  0,  0]], dtype=int32)

In [111]:
(csr*csr).toarray()

array([[  63,  210,    0,   84,    0],
       [   0,    0,   33,  252,    0],
       [   0,    0, 1089,    0,    0],
       [ 132,   40,   10,   79,    0],
       [   0,    0,    0,    0,    0]], dtype=int32)

In [113]:
csr.toarray()

array([[ 0,  0,  0, 21,  0],
       [12,  0,  1,  0,  0],
       [ 0,  0, 33,  0,  0],
       [ 3, 10,  0,  4,  0],
       [ 0,  0,  0,  0,  0]], dtype=int32)

## np.cross 向量叉乘

In [130]:
x=[1,2]
y=[3,2]
np.cross(x,y)

array(-4)

In [133]:
x=[1,2,4]
y=[3,2,5]
np.cross(x,y)

array([ 2,  7, -4])

In [135]:
x=[1,2,0]
x_1=[1,2]
y=[3,2,3]
print(np.cross(x_1,y),np.cross(x,y)) # 会自动用0补齐

[ 6 -3 -4] [ 6 -3 -4]
