In [4]:
import numpy as np

In [7]:
p=3 # 多项式 基函数 的 次数
c=np.arange(1,p+1)
p=1/np.multiply.accumulate(c)

array([1, 2, 3])

In [8]:
display(np.multiply.accumulate(c),1/np.multiply.accumulate(c))

array([1, 2, 6], dtype=int32)

array([1.        , 0.5       , 0.16666667])

In [13]:
bc=np.array([[1/3,1/3,1/3]])
bc

array([[0.33333333, 0.33333333, 0.33333333]])